### ISSUE TITLE
map tiles

### ISSUE THREAD

**Issue by rofl0r** [marfsama/colsaves#1]
hi, i see you got code there to render the map from a savegame, however the .png's are missing here in this repo. could you provide them somewhere so i can test the functionality ?

**Comment by marfsama** [comment]
I've extracted them somehow from the original files, so these are the original graphics. As these are still intellectual property unfortunately I can not provide them.
I think I've used https://github.com/institution/mpskit to extract the images.

**Comment by rofl0r** [comment]
shitting his pants for a couple assets from 30year old game... gotcha.

**Comment by marfsama** [comment]
Be nice my friend. You can buy this game for 2 bucks on steam or gog, so you won't starve by supporting the oroginal developers. Go buy the game.
